- hosts: localhost
  gather_facts: no
  vars_files: vars/dnac_vars.yaml
  vars:
    dnac_conn: &dnac_conn
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_verify: "{{dnac_verify}}"
        dnac_port: "{{dnac_port}}"
        dnac_version: "{{dnac_version}}"
        dnac_debug: "{{dnac_debug}}"    
        headers: "{{my_headers | from_json}}"
        ipAddress: string

  tasks:
    - name: Get Network Device By Ip by id
      cisco.dnac.network_device_by_ip_info:
        <<: *dnac_conn
        summary: true
      register: result

    - name: Show Devices
      debug:
        msg:
          - "{{ result }}"
