name: Record Traffic Insights

on:
  push:
    branches:
      - master 
  schedule:
    - cron: '0 0 */14 * *'  # Runs every 14 days at midnight UTC

jobs:
  log-traffic-insights:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 pdfkit
          sudo apt-get install -y wkhtmltopdf  # Install wkhtmltopdf

      - name: Run traffic insights script
        env:
          ACCESS_TOKEN: ${{ secrets.KEY }}  # Use GitHub token or set your own secret
          OWNER: ${{ secrets.USERNAME }}  # Replace with your GitHub username
          REPO: ${{ secrets.REPO }}  # Replace with your repository name
        run: |
          mkdir -p /CODE/TRAFFIC  # Create the directory if it doesn't exist
          python /CODE/SCRIPTS/logging.py
      
      - name: Upload CSV Log
        uses: actions/upload-artifact@v2
        with:
          name: traffic_log
          path: /CODE/TRAFFIC/traffic_log.csv   # Adjust path if necessary
